apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: vllm
  name: vllm
  namespace: llama-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vllm
      annotations:
        sidecar.opentelemetry.io/inject: otelsidecar
    spec:
      containers:
      - args:
        - --model
        - meta-llama/Llama-3.2-3B-Instruct
        - --enable-auto-tool-choice
        - --chat-template
        - /app/tool_chat_template_llama3.2_json.jinja
        - --tool-call-parser
        - llama3_json
        - --port
        - "8000"
        env:
        - name: VLLM_PORT
          value: "8000"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: huggingface-secret
        image: vllm/vllm-openai:latest
        imagePullPolicy: Always
        name: vllm
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /.cache
          name: hf-cache
        - mountPath: /app
          name: chat-template
        - mountPath: /.config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: hf-cache
      - configMap:
          defaultMode: 420
          name: template
        name: chat-template
      - emptyDir: {}
        name: config